// Auto-generated by update-deals.ts
// Last updated: 2026-01-24T20:16:08.659Z
// Run 'npm run update-deals' to refresh deals

export const lastUpdated = 'January 24, 2026'

export interface Deal {
  id: string
  origin: string
  destination: string
  destinationCity: string
  destinationCountry: string
  price: number
  normalPrice: number
  savings: number
  airline: string
  stops: number
  dates: string
  expiresAt?: string
}

export const dealsByAirport: Record<string, Deal[]> = {
  "JFK": [
    {
      "id": "jfk-cdg-1",
      "origin": "JFK",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 273,
      "normalPrice": 850,
      "savings": 577,
      "airline": "Multiple Airlines",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "jfk-bcn-2",
      "origin": "JFK",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 293,
      "normalPrice": 780,
      "savings": 487,
      "airline": "TAP Portugal",
      "stops": 1,
      "dates": "Mar - May 2026"
    },
    {
      "id": "jfk-dub-3",
      "origin": "JFK",
      "destination": "DUB",
      "destinationCity": "Dublin",
      "destinationCountry": "Ireland",
      "price": 207,
      "normalPrice": 620,
      "savings": 413,
      "airline": "Aer Lingus",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "jfk-nrt-4",
      "origin": "JFK",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 510,
      "normalPrice": 1400,
      "savings": 890,
      "airline": "ANA",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "jfk-lis-5",
      "origin": "JFK",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 296,
      "normalPrice": 690,
      "savings": 394,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "LAX": [
    {
      "id": "lax-nrt-1",
      "origin": "LAX",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 375,
      "normalPrice": 1200,
      "savings": 825,
      "airline": "Japan Airlines",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "lax-syd-2",
      "origin": "LAX",
      "destination": "SYD",
      "destinationCity": "Sydney",
      "destinationCountry": "Australia",
      "price": 555,
      "normalPrice": 1500,
      "savings": 945,
      "airline": "Qantas",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "lax-cdg-3",
      "origin": "LAX",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 328,
      "normalPrice": 950,
      "savings": 622,
      "airline": "Air France",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "lax-fco-4",
      "origin": "LAX",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 456,
      "normalPrice": 1100,
      "savings": 644,
      "airline": "ITA Airways",
      "stops": 1,
      "dates": "Mar - May 2026"
    },
    {
      "id": "lax-cun-5",
      "origin": "LAX",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 176,
      "normalPrice": 450,
      "savings": 274,
      "airline": "American Airlines",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "LHR": [
    {
      "id": "lhr-jfk-1",
      "origin": "LHR",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 327,
      "normalPrice": 850,
      "savings": 523,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "lhr-dxb-2",
      "origin": "LHR",
      "destination": "DXB",
      "destinationCity": "Dubai",
      "destinationCountry": "UAE",
      "price": 350,
      "normalPrice": 800,
      "savings": 450,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "lhr-bkk-3",
      "origin": "LHR",
      "destination": "BKK",
      "destinationCity": "Bangkok",
      "destinationCountry": "Thailand",
      "price": 360,
      "normalPrice": 950,
      "savings": 590,
      "airline": "Thai Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "lhr-bcn-4",
      "origin": "LHR",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 44,
      "normalPrice": 180,
      "savings": 136,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "lhr-fco-5",
      "origin": "LHR",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 47,
      "normalPrice": 200,
      "savings": 153,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Feb - May 2026"
    }
  ],
  "DXB": [
    {
      "id": "dxb-lhr-1",
      "origin": "DXB",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 334,
      "normalPrice": 900,
      "savings": 566,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "dxb-bkk-2",
      "origin": "DXB",
      "destination": "BKK",
      "destinationCity": "Bangkok",
      "destinationCountry": "Thailand",
      "price": 264,
      "normalPrice": 650,
      "savings": 386,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "dxb-sin-3",
      "origin": "DXB",
      "destination": "SIN",
      "destinationCity": "Singapore",
      "destinationCountry": "Singapore",
      "price": 336,
      "normalPrice": 750,
      "savings": 414,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "dxb-mle-4",
      "origin": "DXB",
      "destination": "MLE",
      "destinationCity": "Maldives",
      "destinationCountry": "Maldives",
      "price": 246,
      "normalPrice": 600,
      "savings": 354,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "dxb-cdg-5",
      "origin": "DXB",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 305,
      "normalPrice": 850,
      "savings": 545,
      "airline": "Air France",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "ORD": [
    {
      "id": "ord-cdg-1",
      "origin": "ORD",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 361,
      "normalPrice": 950,
      "savings": 589,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "ord-lhr-2",
      "origin": "ORD",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 413,
      "normalPrice": 1000,
      "savings": 587,
      "airline": "American Airlines",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "ord-cun-3",
      "origin": "ORD",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 174,
      "normalPrice": 450,
      "savings": 276,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "ord-nrt-4",
      "origin": "ORD",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 515,
      "normalPrice": 1300,
      "savings": 785,
      "airline": "ANA",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "ord-fco-5",
      "origin": "ORD",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 457,
      "normalPrice": 1100,
      "savings": 643,
      "airline": "ITA Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "CDG": [
    {
      "id": "cdg-jfk-1",
      "origin": "CDG",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 276,
      "normalPrice": 850,
      "savings": 574,
      "airline": "Air France",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "cdg-nrt-2",
      "origin": "CDG",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 423,
      "normalPrice": 1200,
      "savings": 777,
      "airline": "Air France",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "cdg-mad-3",
      "origin": "CDG",
      "destination": "MAD",
      "destinationCity": "Madrid",
      "destinationCountry": "Spain",
      "price": 49,
      "normalPrice": 180,
      "savings": 131,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "cdg-bcn-4",
      "origin": "CDG",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 44,
      "normalPrice": 160,
      "savings": 116,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "cdg-dxb-5",
      "origin": "CDG",
      "destination": "DXB",
      "destinationCity": "Dubai",
      "destinationCountry": "UAE",
      "price": 310,
      "normalPrice": 800,
      "savings": 490,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    }
  ],
  "FRA": [
    {
      "id": "fra-jfk-1",
      "origin": "FRA",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 376,
      "normalPrice": 900,
      "savings": 524,
      "airline": "Lufthansa",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "fra-nrt-2",
      "origin": "FRA",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 491,
      "normalPrice": 1150,
      "savings": 659,
      "airline": "Lufthansa",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "fra-bkk-3",
      "origin": "FRA",
      "destination": "BKK",
      "destinationCity": "Bangkok",
      "destinationCountry": "Thailand",
      "price": 436,
      "normalPrice": 950,
      "savings": 514,
      "airline": "Thai Airways",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "fra-bcn-4",
      "origin": "FRA",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 57,
      "normalPrice": 200,
      "savings": 143,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "fra-lis-5",
      "origin": "FRA",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 66,
      "normalPrice": 220,
      "savings": 154,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    }
  ],
  "SFO": [
    {
      "id": "sfo-nrt-1",
      "origin": "SFO",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 440,
      "normalPrice": 1200,
      "savings": 760,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "sfo-syd-2",
      "origin": "SFO",
      "destination": "SYD",
      "destinationCity": "Sydney",
      "destinationCountry": "Australia",
      "price": 581,
      "normalPrice": 1600,
      "savings": 1019,
      "airline": "Qantas",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "sfo-cdg-3",
      "origin": "SFO",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 447,
      "normalPrice": 1050,
      "savings": 603,
      "airline": "Air France",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "sfo-lhr-4",
      "origin": "SFO",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 453,
      "normalPrice": 1100,
      "savings": 647,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "sfo-cun-5",
      "origin": "SFO",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 225,
      "normalPrice": 500,
      "savings": 275,
      "airline": "United Airlines",
      "stops": 1,
      "dates": "Mar - May 2026"
    }
  ],
  "AMS": [
    {
      "id": "ams-jfk-1",
      "origin": "AMS",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 306,
      "normalPrice": 850,
      "savings": 544,
      "airline": "KLM",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "ams-nrt-2",
      "origin": "AMS",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 435,
      "normalPrice": 1100,
      "savings": 665,
      "airline": "KLM",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "ams-bcn-3",
      "origin": "AMS",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 48,
      "normalPrice": 180,
      "savings": 132,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "ams-lis-4",
      "origin": "AMS",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 58,
      "normalPrice": 200,
      "savings": 142,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "ams-dxb-5",
      "origin": "AMS",
      "destination": "DXB",
      "destinationCity": "Dubai",
      "destinationCountry": "UAE",
      "price": 329,
      "normalPrice": 850,
      "savings": 521,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    }
  ],
  "MAD": [
    {
      "id": "mad-jfk-1",
      "origin": "MAD",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 300,
      "normalPrice": 850,
      "savings": 550,
      "airline": "Iberia",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "mad-mia-2",
      "origin": "MAD",
      "destination": "MIA",
      "destinationCity": "Miami",
      "destinationCountry": "USA",
      "price": 345,
      "normalPrice": 900,
      "savings": 555,
      "airline": "Iberia",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "mad-lhr-3",
      "origin": "MAD",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 54,
      "normalPrice": 200,
      "savings": 146,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "mad-cdg-4",
      "origin": "MAD",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 44,
      "normalPrice": 180,
      "savings": 136,
      "airline": "Air France",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "mad-fco-5",
      "origin": "MAD",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 45,
      "normalPrice": 170,
      "savings": 125,
      "airline": "ITA Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "BCN": [
    {
      "id": "bcn-jfk-1",
      "origin": "BCN",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 346,
      "normalPrice": 900,
      "savings": 554,
      "airline": "LEVEL",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "bcn-lhr-2",
      "origin": "BCN",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 46,
      "normalPrice": 180,
      "savings": 134,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "bcn-cdg-3",
      "origin": "BCN",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 38,
      "normalPrice": 150,
      "savings": 112,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "bcn-ams-4",
      "origin": "BCN",
      "destination": "AMS",
      "destinationCity": "Amsterdam",
      "destinationCountry": "Netherlands",
      "price": 45,
      "normalPrice": 180,
      "savings": 135,
      "airline": "KLM",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "bcn-fco-5",
      "origin": "BCN",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 42,
      "normalPrice": 160,
      "savings": 118,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    }
  ],
  "BOS": [
    {
      "id": "bos-dub-1",
      "origin": "BOS",
      "destination": "DUB",
      "destinationCity": "Dublin",
      "destinationCountry": "Ireland",
      "price": 286,
      "normalPrice": 700,
      "savings": 414,
      "airline": "Aer Lingus",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "bos-lhr-2",
      "origin": "BOS",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 361,
      "normalPrice": 950,
      "savings": 589,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "bos-cdg-3",
      "origin": "BOS",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 365,
      "normalPrice": 900,
      "savings": 535,
      "airline": "Air France",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "bos-bcn-4",
      "origin": "BOS",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 328,
      "normalPrice": 850,
      "savings": 522,
      "airline": "TAP Portugal",
      "stops": 1,
      "dates": "Feb - May 2026"
    },
    {
      "id": "bos-lis-5",
      "origin": "BOS",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 300,
      "normalPrice": 750,
      "savings": 450,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Feb - May 2026"
    }
  ],
  "MIA": [
    {
      "id": "mia-mad-1",
      "origin": "MIA",
      "destination": "MAD",
      "destinationCity": "Madrid",
      "destinationCountry": "Spain",
      "price": 304,
      "normalPrice": 900,
      "savings": 596,
      "airline": "Iberia",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "mia-cdg-2",
      "origin": "MIA",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 348,
      "normalPrice": 950,
      "savings": 602,
      "airline": "Air France",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "mia-lhr-3",
      "origin": "MIA",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 360,
      "normalPrice": 1000,
      "savings": 640,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "mia-cun-4",
      "origin": "MIA",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 117,
      "normalPrice": 350,
      "savings": 233,
      "airline": "American Airlines",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "mia-gru-5",
      "origin": "MIA",
      "destination": "GRU",
      "destinationCity": "São Paulo",
      "destinationCountry": "Brazil",
      "price": 402,
      "normalPrice": 950,
      "savings": 548,
      "airline": "LATAM",
      "stops": 0,
      "dates": "Feb - May 2026"
    }
  ],
  "EWR": [
    {
      "id": "ewr-cdg-1",
      "origin": "EWR",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 306,
      "normalPrice": 850,
      "savings": 544,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "ewr-lhr-2",
      "origin": "EWR",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 326,
      "normalPrice": 900,
      "savings": 574,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "ewr-bcn-3",
      "origin": "EWR",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 308,
      "normalPrice": 800,
      "savings": 492,
      "airline": "TAP Portugal",
      "stops": 1,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "ewr-lis-4",
      "origin": "EWR",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 258,
      "normalPrice": 720,
      "savings": 462,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "ewr-dub-5",
      "origin": "EWR",
      "destination": "DUB",
      "destinationCity": "Dublin",
      "destinationCountry": "Ireland",
      "price": 262,
      "normalPrice": 650,
      "savings": 388,
      "airline": "Aer Lingus",
      "stops": 0,
      "dates": "Feb - May 2026"
    }
  ],
  "ATL": [
    {
      "id": "atl-cdg-1",
      "origin": "ATL",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 397,
      "normalPrice": 950,
      "savings": 553,
      "airline": "Delta",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "atl-lhr-2",
      "origin": "ATL",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 380,
      "normalPrice": 1000,
      "savings": 620,
      "airline": "Delta",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "atl-cun-3",
      "origin": "ATL",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 195,
      "normalPrice": 450,
      "savings": 255,
      "airline": "Delta",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "atl-fco-4",
      "origin": "ATL",
      "destination": "FCO",
      "destinationCity": "Rome",
      "destinationCountry": "Italy",
      "price": 462,
      "normalPrice": 1100,
      "savings": 638,
      "airline": "Delta",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "atl-ams-5",
      "origin": "ATL",
      "destination": "AMS",
      "destinationCity": "Amsterdam",
      "destinationCountry": "Netherlands",
      "price": 346,
      "normalPrice": 950,
      "savings": 604,
      "airline": "KLM",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    }
  ],
  "MUC": [
    {
      "id": "muc-jfk-1",
      "origin": "MUC",
      "destination": "JFK",
      "destinationCity": "New York",
      "destinationCountry": "USA",
      "price": 374,
      "normalPrice": 950,
      "savings": 576,
      "airline": "Lufthansa",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "muc-nrt-2",
      "origin": "MUC",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 473,
      "normalPrice": 1200,
      "savings": 727,
      "airline": "Lufthansa",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "muc-bcn-3",
      "origin": "MUC",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 57,
      "normalPrice": 200,
      "savings": 143,
      "airline": "Vueling",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "muc-lis-4",
      "origin": "MUC",
      "destination": "LIS",
      "destinationCity": "Lisbon",
      "destinationCountry": "Portugal",
      "price": 58,
      "normalPrice": 230,
      "savings": 172,
      "airline": "TAP Portugal",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "muc-dxb-5",
      "origin": "MUC",
      "destination": "DXB",
      "destinationCity": "Dubai",
      "destinationCountry": "UAE",
      "price": 388,
      "normalPrice": 850,
      "savings": 462,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - May 2026"
    }
  ],
  "SEA": [
    {
      "id": "sea-nrt-1",
      "origin": "SEA",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 458,
      "normalPrice": 1150,
      "savings": 692,
      "airline": "Delta",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "sea-cdg-2",
      "origin": "SEA",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 411,
      "normalPrice": 1100,
      "savings": 689,
      "airline": "Air France",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "sea-lhr-3",
      "origin": "SEA",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 415,
      "normalPrice": 1150,
      "savings": 735,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "sea-cun-4",
      "origin": "SEA",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 294,
      "normalPrice": 600,
      "savings": 306,
      "airline": "Alaska Airlines",
      "stops": 1,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "sea-icn-5",
      "origin": "SEA",
      "destination": "ICN",
      "destinationCity": "Seoul",
      "destinationCountry": "South Korea",
      "price": 517,
      "normalPrice": 1200,
      "savings": 683,
      "airline": "Korean Air",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    }
  ],
  "DEN": [
    {
      "id": "den-lhr-1",
      "origin": "DEN",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 442,
      "normalPrice": 1100,
      "savings": 658,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "den-cdg-2",
      "origin": "DEN",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 389,
      "normalPrice": 1050,
      "savings": 661,
      "airline": "United Airlines",
      "stops": 1,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "den-cun-3",
      "origin": "DEN",
      "destination": "CUN",
      "destinationCity": "Cancun",
      "destinationCountry": "Mexico",
      "price": 229,
      "normalPrice": 500,
      "savings": 271,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "den-nrt-4",
      "origin": "DEN",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 507,
      "normalPrice": 1300,
      "savings": 793,
      "airline": "United Airlines",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "den-fra-5",
      "origin": "DEN",
      "destination": "FRA",
      "destinationCity": "Frankfurt",
      "destinationCountry": "Germany",
      "price": 381,
      "normalPrice": 1000,
      "savings": 619,
      "airline": "Lufthansa",
      "stops": 0,
      "dates": "Mar - May 2026"
    }
  ],
  "SYD": [
    {
      "id": "syd-lax-1",
      "origin": "SYD",
      "destination": "LAX",
      "destinationCity": "Los Angeles",
      "destinationCountry": "USA",
      "price": 652,
      "normalPrice": 1500,
      "savings": 848,
      "airline": "Qantas",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "syd-lhr-2",
      "origin": "SYD",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 766,
      "normalPrice": 2000,
      "savings": 1234,
      "airline": "Qantas",
      "stops": 1,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "syd-nrt-3",
      "origin": "SYD",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 500,
      "normalPrice": 1100,
      "savings": 600,
      "airline": "Japan Airlines",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "syd-sin-4",
      "origin": "SYD",
      "destination": "SIN",
      "destinationCity": "Singapore",
      "destinationCountry": "Singapore",
      "price": 333,
      "normalPrice": 750,
      "savings": 417,
      "airline": "Singapore Airlines",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "syd-dxb-5",
      "origin": "SYD",
      "destination": "DXB",
      "destinationCity": "Dubai",
      "destinationCountry": "UAE",
      "price": 739,
      "normalPrice": 1600,
      "savings": 861,
      "airline": "Emirates",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    }
  ],
  "YYZ": [
    {
      "id": "yyz-lhr-1",
      "origin": "YYZ",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 447,
      "normalPrice": 1000,
      "savings": 553,
      "airline": "Air Canada",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "yyz-cdg-2",
      "origin": "YYZ",
      "destination": "CDG",
      "destinationCity": "Paris",
      "destinationCountry": "France",
      "price": 480,
      "normalPrice": 1050,
      "savings": 570,
      "airline": "Air France",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "yyz-bcn-3",
      "origin": "YYZ",
      "destination": "BCN",
      "destinationCity": "Barcelona",
      "destinationCountry": "Spain",
      "price": 415,
      "normalPrice": 980,
      "savings": 565,
      "airline": "Air Canada",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "yyz-nrt-4",
      "origin": "YYZ",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 611,
      "normalPrice": 1500,
      "savings": 889,
      "airline": "Air Canada",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "yyz-dub-5",
      "origin": "YYZ",
      "destination": "DUB",
      "destinationCity": "Dublin",
      "destinationCountry": "Ireland",
      "price": 391,
      "normalPrice": 900,
      "savings": 509,
      "airline": "Aer Lingus",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    }
  ],
  "HKG": [
    {
      "id": "hkg-nrt-1",
      "origin": "HKG",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 198,
      "normalPrice": 550,
      "savings": 352,
      "airline": "Cathay Pacific",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "hkg-bkk-2",
      "origin": "HKG",
      "destination": "BKK",
      "destinationCity": "Bangkok",
      "destinationCountry": "Thailand",
      "price": 145,
      "normalPrice": 380,
      "savings": 235,
      "airline": "Hong Kong Airlines",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "hkg-syd-3",
      "origin": "HKG",
      "destination": "SYD",
      "destinationCity": "Sydney",
      "destinationCountry": "Australia",
      "price": 489,
      "normalPrice": 1200,
      "savings": 711,
      "airline": "Qantas",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "hkg-lhr-4",
      "origin": "HKG",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 520,
      "normalPrice": 1350,
      "savings": 830,
      "airline": "British Airways",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "hkg-sin-5",
      "origin": "HKG",
      "destination": "SIN",
      "destinationCity": "Singapore",
      "destinationCountry": "Singapore",
      "price": 168,
      "normalPrice": 420,
      "savings": 252,
      "airline": "Singapore Airlines",
      "stops": 0,
      "dates": "Mar - Apr 2026"
    }
  ],
  "SIN": [
    {
      "id": "sin-bkk-1",
      "origin": "SIN",
      "destination": "BKK",
      "destinationCity": "Bangkok",
      "destinationCountry": "Thailand",
      "price": 89,
      "normalPrice": 250,
      "savings": 161,
      "airline": "Singapore Airlines",
      "stops": 0,
      "dates": "Feb - Apr 2026"
    },
    {
      "id": "sin-nrt-2",
      "origin": "SIN",
      "destination": "NRT",
      "destinationCity": "Tokyo",
      "destinationCountry": "Japan",
      "price": 298,
      "normalPrice": 750,
      "savings": 452,
      "airline": "ANA",
      "stops": 0,
      "dates": "Mar - May 2026"
    },
    {
      "id": "sin-mel-3",
      "origin": "SIN",
      "destination": "MEL",
      "destinationCity": "Melbourne",
      "destinationCountry": "Australia",
      "price": 345,
      "normalPrice": 850,
      "savings": 505,
      "airline": "Scoot",
      "stops": 0,
      "dates": "Mar - Jun 2026"
    },
    {
      "id": "sin-icn-4",
      "origin": "SIN",
      "destination": "ICN",
      "destinationCity": "Seoul",
      "destinationCountry": "South Korea",
      "price": 278,
      "normalPrice": 680,
      "savings": 402,
      "airline": "Korean Air",
      "stops": 0,
      "dates": "Feb - May 2026"
    },
    {
      "id": "sin-lhr-5",
      "origin": "SIN",
      "destination": "LHR",
      "destinationCity": "London",
      "destinationCountry": "UK",
      "price": 485,
      "normalPrice": 1250,
      "savings": 765,
      "airline": "Singapore Airlines",
      "stops": 0,
      "dates": "Mar - Apr 2026"
    }
  ]
}

export function getDealsForAirport(code: string): Deal[] {
  return dealsByAirport[code.toUpperCase()] || []
}

export function getDealsForCity(airports: string[]): Deal[] {
  const allDeals: Deal[] = []
  for (const code of airports) {
    const deals = getDealsForAirport(code)
    allDeals.push(...deals)
  }
  return allDeals
}

export function getFeaturedDeals(): Deal[] {
  // Return a mix of deals from different airports
  const featured: Deal[] = []
  const airportCodes = Object.keys(dealsByAirport)

  for (let i = 0; i < Math.min(8, airportCodes.length); i++) {
    const deals = dealsByAirport[airportCodes[i]]
    if (deals && deals.length > 0) {
      featured.push(deals[0])
    }
  }

  return featured
}
